### ISSUE TITLE
Einarbeiten von CSS Eigenschaften in Tutorials

### ISSUE THREAD

**Issue by Rolf-B** [SELFHTML/SelfTrack#11]
Die folgenden Unterseiten zu CSS Eigenschaften müssen noch einsortiert werden und bräuchten bessere Erklärungen

* [CSS/Eigenschaften/Anzeige/opacity](https://wiki.selfhtml.org/wiki/CSS/Eigenschaften/Anzeige/opacity)
* [CSS/Eigenschaften/Anzeige/visibility](https://wiki.selfhtml.org/wiki/CSS/Eigenschaften/Anzeige/visibiliy)

**Comment by Matthias-Scharwies** [comment]
accent-color
* [CSS/Eigenschaften/appearance](https://wiki.selfhtml.org/wiki/CSS/Eigenschaften/appearance)
* [CSS/Eigenschaften/caret-color](https://wiki.selfhtml.org/wiki/CSS/Eigenschaften/caret-color)
* [CSS/Eigenschaften/cursor](https://wiki.selfhtml.org/wiki/CSS/Eigenschaften/cursor)
* [CSS/Eigenschaften/user-select](https://wiki.selfhtml.org/wiki/CSS/Eigenschaften/user-select)

Jetzt im Tutorial [Benutzeroberfläche](https://wiki.selfhtml.org/wiki/CSS/Tutorials/Benutzeroberfl%C3%A4che)

**Comment by Matthias-Scharwies** [comment]
Sind zu CSS/Tutorials verschoben worden
