### ISSUE TITLE
Vorlage für Caniuse - Full Link

### ISSUE THREAD

**Issue by Rolf-B** [SELFHTML/SelfTrack#22]
Canuise Vorlage liefert ein Caniuse-Symbol, wo weder der Globus noch "Browserunterstützung" klickbar ist.

**Comment by Rolf-B** [comment]
Im Wesentlichen fertig, Farben müssten nochmal begutachtet werden. Mit Standardfarben (--blue auf --green3) its es zu wenig Kontrast, und --blue auf --white ist ööööde ;-)

BTW habe ich das Welt-Icon nochmal angefasst und auf 0 0 100 100 Viewbox skaliert. Weniger Bytes ;-)

**Comment by Matthias-Scharwies** [comment]
Ich habe die Linkfarbe auf `color: var(--black1);` gesetzt -> Kontrast 1:9 -läuft!

[Hilfe:Farbtabelle](https://wiki.selfhtml.org/wiki/Hilfe:Farbtabelle#abgestufte_Farbt.C3.B6ne)
