### ISSUE TITLE
Visualisierung des Bubblings erstellen

### ISSUE THREAD

**Issue by Rolf-B** [SELFHTML/SelfTrack#3]
Auftrag aus MV 2021

**Comment by J-Berkemeier** [comment]
Aktueller Stand hier:
[https://wiki.selfhtml.org/wiki/Benutzer:JürgenB#Bubbling.2C_Capturing_und_stopPropagation](https://wiki.selfhtml.org/wiki/Benutzer:JürgenB#Bubbling.2C_Capturing_und_stopPropagation)

**Comment by J-Berkemeier** [comment]
Ich habe Text und Script jetzt aus meinem Bereich ins Wiki kopiert:

[https://wiki.selfhtml.org/wiki/JavaScript/Tutorials/DOM/Ereignisverarbeitung#Bubbling.2C_Capturing_und_stopPropagation](https://wiki.selfhtml.org/wiki/JavaScript/Tutorials/DOM/Ereignisverarbeitung#Bubbling.2C_Capturing_und_stopPropagation)

[https://wiki.selfhtml.org/wiki/JavaScript/DOM/Event/Ereignisbehandlung#Die_drei_Ereignisphasen](https://wiki.selfhtml.org/wiki/JavaScript/DOM/Event/Ereignisbehandlung#Die_drei_Ereignisphasen)

**Comment by Rolf-B** [comment]
Da sehe ich ein Folge-Todo. Diese beiden Artikel überschneiden sich inhaltlich zu sehr, da muss sortiert werden.

Ich glaube auch einen Verständnisfehler in der Beschreibung zu erkennen: Da wird an einer Stelle angedeutet, es gäbe **erst** die Bubbling und **dann** die Capturing-Phase. Das ist falsch. Die Reihenfolge ist:
- Event wird an einem Element getriggert (event.target)
- Browser bildet die Elternkette vom event.target bis zum Root-Element (wo ich nicht ganz sicher bin, ob das <html> ist oder ein übergeordneter Dummy. Chrome zeigt mir bei document.getRootNode() ein #document Pseudoelement
- Capturing: Browser durchläuft die Elternkette vom Root zum Target (inklusive!) und ruft die Eventhandler auf, die für capturing registriert sind. Beim Aufruf ist event.currentTarget das Element, für das der Handler registriert ist. event.stopPropagation bricht das Capturing ab, das Event gelangt nicht weiter nach innen.
- Bubbling: Browser durchläuft die Elternkette vom Target (inklusive!) zum Root und ruft die Eventhandler auf, die nicht für capturing registriert sind. Beim Aufruf ist event.currentTarget das Element, für das der Handler registriert ist. event.stopPropagation bricht das Bubbling ab, das Event gelangt nicht weiter nach außen.

Deswegen hatte ich ja auch meine Verwunderung darüber, dass Du beim down-Event das Bubbling zeigst und beim up-Event das Capturing. 

Wenn Du das Folgetodo selbst übernehmen magst, halte ich mich 'raus. Ich kann es auch übernehmen (oder es findet sich ein anderer Interessent...)

**Comment by J-Berkemeier** [comment]
Ich kümmere mich darum. Das mit den Eventphasen habe ich wirklich falsch verstanden. Ich dachte, die Events gingen vom Element aus Richtung html-Element und wieder zurück, also bubbling vor capturing.

Kann das Beispiel denn so bleiben,  mit down -> bubling, und up -> capturing? Oder soll ich das besser vertauschen?

Oder nur ein Klick mit beidem?

**Comment by Rolf-B** [comment]
Ich würd's vertauschen, und pro Event auch nur eine Richtung zeigen. Du hast den Visualisierungscode ja als Teil des Tutorials eingebaut. Der sollte also nicht zu komplex werden. 

Aber ich träume von einer Visualisierung, wo nach einem Event ein Event-Bubble in Form eines blauen Kreises (ein Seifenbläschen) von Rechteck zu Rechteck fliegt - animiert - und dabei erst Capturing und dann Bubbling zeigt. Ein neues Event bringt ein neues Event-Bubble auf den Weg, das unabhängig vom ersten Bubble fliegt. Mit Hilfe von absoluter Positionierung und einem transition-Effekt für top und left könnte das machbar sein, aber es ist vermutlich viel zu komplex, um es im Wiki als Beispielcode zu zeigen. Das wäre ein Tutorial für Fortgeschrittene. Wobei - geil wär's schon. Im Bereich des Eventhandling, was ein Einsteigerteil ist, zeigt man es nur als Visualisierungstool. Und im Bereich JavaScript bringt man den Bau dieser Visualisierung als Tutorial für eine Kombi von JS + CSS für Animation. Vielleicht sogar in einem SVG (muss aber nicht, aber es würde Matthias vermutlich begeistern), Würde es Dir Spaß machen, so was zu erstellen?

**Comment by J-Berkemeier** [comment]
Ich habe die Änderungen ins Wiki gestellt. 

Eine Grafik-Animation wäre schon "lustig", so mit aufstegenden Bläschen ud absteigenden Packmans :). Aber ob das lohnt?

Zu <https://wiki.selfhtml.org/wiki/JavaScript/DOM/Event/Ereignisbehandlung#Die_drei_Ereignisphasen> habe ich keine Idee. Ich habe da mein Beispiel einfach reingelegt, aber ohne mich um den Rest zu kümmern. Da muss sich Matthias zu äußern. Wir können ihn ja beim Srammtisch fragen.
