### ISSUE TITLE
Kurs für Boxmodell erstellen

### ISSUE THREAD

**Issue by Rolf-B** [SELFHTML/SelfTrack#4]
Auftrag aus MV

**Comment by Matthias-Scharwies** [comment]
Zwischenstand: Ich habe jetzt die Kapitel 1-3 fertig:

* [CSS/Tutorials/Boxmodell](https://wiki.selfhtml.org/wiki/CSS/Tutorials/Boxmodell)
     - Der Text zum klassischen Boxmodell ist umgestellt; 
     - Beispiel und Text zu box-sizing gekürzt.
* [CSS/Tutorials/Boxmodell/Größenangaben](https://wiki.selfhtml.org/wiki/CSS/Tutorials/Boxmodell/Gr%C3%B6%C3%9Fenangaben)
     - Beispiele vereinfacht und praxisorientierter
     - Fazit, das vor dem Einsatz dieser Eigenschaften warnt :-9
* [CSS/Tutorials/Boxmodell/übergrßer_Inhalt](https://wiki.selfhtml.org/wiki/CSS/Tutorials/Boxmodell/%C3%BCbergro%C3%9Fer_Inhalt)
     - kontextualisierte, einfache Beispiele
     - Fazit, das vom Einsatz abrät
 
Bitte durchlesen und Verbesserungen vorschlagen!

**Comment by Matthias-Scharwies** [comment]
Logische Eigenschaften: vorerst fertig.

würde es aber gerne im Forum weiterdiskutieren:

[https://forum.selfhtml.org/self/2021/oct/27/self-wiki-boxmodell-und-logische-eigenschaften/1793286#m1793286](https://forum.selfhtml.org/self/2021/oct/27/self-wiki-boxmodell-und-logische-eigenschaften/1793286#m1793286)
