### ISSUE TITLE
Überarbeitung Landing Page

### ISSUE THREAD

**Issue by Rolf-B** [SELFHTML/SelfTrack#8]
Beschluss der [MV beim SELF-Treffen 2021](https://wiki.selfhtml.org/wiki/SELFHTML:Verein/Protokolle/Mitgliederversammlung_2021#Landing_Page_und_Unterst.C3.BCtzerseiten):

* Übertragen der statischen selfhtml.org Startseite ins Wiki
* Redesign der Startseite

**Comment by Matthias-Scharwies** [comment]
Die Landing Page unter selfhtml.org wird depubliziert und stattdessen die Startseite des Wiki verwendet.

Dieser Schritt kann erst vollzogen werden, wenn ...

* klar ist, welche Inhalte **sichtbar** auf der Startseite Platz finden sollen
* UI des Wiki überprüft und ggfalls verändert wird.
     - Vorschlag: Links auf letzte Blog-Artikel, letzte Twitter-Tweets, etc
     - keine alphabetischen Linklisten
     - persönliche Benutzereinstellungen per Popup
     - Bearbeitungsfunktionen für angemeldete Nutzer per Popup
